[2025-04-09T15:46:59.988+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T15:47:00.009+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.extract_weather_data manual__2025-04-09T14:23:50.560402+00:00 [queued]>
[2025-04-09T15:47:00.020+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.extract_weather_data manual__2025-04-09T14:23:50.560402+00:00 [queued]>
[2025-04-09T15:47:00.021+0000] {taskinstance.py:2867} INFO - Starting attempt 5 of 3
[2025-04-09T15:47:00.049+0000] {taskinstance.py:2890} INFO - Executing <Task(HttpOperator): extract_weather_data> on 2025-04-09 14:23:50.560402+00:00
[2025-04-09T15:47:00.060+0000] {standard_task_runner.py:72} INFO - Started process 29616 to run task
[2025-04-09T15:47:00.066+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_dag', 'extract_weather_data', 'manual__2025-04-09T14:23:50.560402+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpebuestn0']
[2025-04-09T15:47:00.070+0000] {standard_task_runner.py:105} INFO - Job 57: Subtask extract_weather_data
[2025-04-09T15:47:00.122+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_dag.extract_weather_data manual__2025-04-09T14:23:50.560402+00:00 [running]> on host ip-172-31-10-226.eu-north-1.compute.internal
[2025-04-09T15:47:00.215+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='myemail@domain.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='extract_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T14:23:50.560402+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T14:23:50.560402+00:00'
[2025-04-09T15:47:00.217+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-09T15:47:00.218+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-09T15:47:00.219+0000] {logging_mixin.py:190} INFO - Current task name:extract_weather_data state:running start_date:2025-04-09 15:47:00.010504+00:00
[2025-04-09T15:47:00.219+0000] {logging_mixin.py:190} INFO - Dag name:weather_dag and current dag run status:running
[2025-04-09T15:47:00.220+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-09T15:47:00.220+0000] {http.py:180} INFO - Calling HTTP method
[2025-04-09T15:47:00.227+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:47:00.233+0000] {base.py:84} INFO - Retrieving connection 'weathermap_api'
[2025-04-09T15:47:00.340+0000] {http.py:241} INFO - {"coord":{"lon":-122.6762,"lat":45.5234},"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04d"}],"base":"stations","main":{"temp":282.14,"feels_like":280.39,"temp_min":280.67,"temp_max":283.4,"pressure":1025,"humidity":92,"sea_level":1025,"grnd_level":1014},"visibility":10000,"wind":{"speed":3.09,"deg":300},"clouds":{"all":75},"dt":1744213565,"sys":{"type":2,"id":2008548,"country":"US","sunrise":1744205709,"sunset":1744253324},"timezone":-25200,"id":5746545,"name":"Portland","cod":200}
[2025-04-09T15:47:00.364+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-09T15:47:00.365+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=extract_weather_data, run_id=manual__2025-04-09T14:23:50.560402+00:00, execution_date=20250409T142350, start_date=20250409T154700, end_date=20250409T154700
[2025-04-09T15:47:00.395+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-04-09T15:47:00.396+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-04-09T15:47:00.396+0000] {logging_mixin.py:190} INFO - Dag name:weather_dag queued_at:2025-04-09 14:23:50.602826+00:00
[2025-04-09T15:47:00.397+0000] {logging_mixin.py:190} INFO - Task hostname:ip-172-31-10-226.eu-north-1.compute.internal operator:HttpOperator
[2025-04-09T15:47:00.444+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-09T15:47:00.471+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-09T15:47:00.478+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-09T15:47:39.097+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T15:47:39.117+0000] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: weather_dag.extract_weather_data manual__2025-04-09T14:23:50.560402+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2025-04-09T15:47:39.119+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
