[2025-04-09T15:22:37.528+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T15:22:37.548+0000] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: weather_dag.is_weather_api_ready manual__2025-04-09T13:43:38.197445+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-04-09T15:22:37.567+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
